{
    "config": {
        "abort": {
            "already_configured": "Usługa jest juz skonfigurowana",
            "cannot_connect": "Nie można nawiązać połączenia"
        },
        "error": {
            "cannot_connect": "Nie można nawiązać połączenia",
            "unknown": "Nieoczekiwany błąd"
        },
        "step": {
            "user": {
                "data": {
                    "station_id": "Stacja pogodowa"
                }
            }
        }
    },
    "exceptions": {
        "cannot_connect": {
            "message": "Wystąpił błąd podczas łączenia się z API IMGW-PIB dla {entry}"
        },
        "update_error": {
            "message": "Wystąpił błąd podczas pobierania danych z API IMGW-PIB dla {entry}"
        }
    }
}
